// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz1lmaw6Zv_f61HA7TYz83yMOP4-Ic0P4',
    appId: '1:304599420586:android:2fed4e2fdd160907228ad3',
    messagingSenderId: '304599420586',
    projectId: 'hansung-univ-noti-noti',
    databaseURL: 'https://hansung-univ-noti-noti-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hansung-univ-noti-noti.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ_HGyyNubqNRQcXEBk5IfV0HsCzgb--8',
    appId: '1:304599420586:ios:136c4a19a16bc09d228ad3',
    messagingSenderId: '304599420586',
    projectId: 'hansung-univ-noti-noti',
    databaseURL: 'https://hansung-univ-noti-noti-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hansung-univ-noti-noti.appspot.com',
    iosClientId: '304599420586-o2rf2rq0jbcucrptjdan8dkv33deoj8f.apps.googleusercontent.com',
    iosBundleId: 'com.finnyjakey.hansungunivnotinoti',
  );
}
